config/routes.rb
Rails.application.routes.draw do
  get 'food_calc/index'
  
  resources :recipes do
    resources :ingredients
  end
    
  resources :ingredients

    
  
  root 'food_calc#index'

  match ':controller(/:action(/:id))', :via => :get
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  
  validates :name, presence: true,
                    length: { minimum: 2 }
  
  validates :avgSize, presence: true,
                    length: { minimum: 1 }
  
  validates :calories, presence: true,
                    length: { minimum: 1 }
  
  validates :toFat, presence: true,
                    length: { minimum: 1 }
  
  validates :chol, presence: true,
                    length: { minimum: 1 }
  
  validates :sod, presence: true,
                    length: { minimum: 1 }
  
  validates :pot, presence: true,
                    length: { minimum: 1 }
  
  validates :totalCarbs, presence: true,
                    length: { minimum: 1 }
  
  validates :diFi, presence: true,
                    length: { minimum: 1 }
  
  validates :sugs, presence: true,
                    length: { minimum: 1 }

  validates :pro, presence: true,
                    length: { minimum: 1 }
  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :ingredients
  validates :title, presence: true, 
                  length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_calc_controller.rb
class FoodCalcController < ApplicationController
  def index
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  
  
  def show
    @ingredient = Ingredient.find(params[:id])
  end
  
  
  def new
    @ingredient = Ingredient.new
  end 
  
  
  def edit
    @ingredient = Ingredient.find(params[:id])
  end 

  
  def create
    @ingredient = Ingredient.new(ingredient_params)
    
    respond_to do |format|
      if @ingredient.save
        format.html { redirect_to @ingredient, notice: 'Ingredient was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end 
  
  
  def update
        @ingredient = Ingredient.find(params[:id])
  
    if @ingredient.update(ingredient_params)
        redirect_to @ingredient
    else
      render 'edit'
    end
  end
  
  
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy
    
    redirect_to ingredients_path
  end
  
  
    private
    def ingredient_params
        params.require(:ingredient).permit(:name, :avgSize, :calories, :toFat, :chol, :sod, :pot, :totalCarbs, :diFi, :sugs, :pro)
    end
  
  
end 

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  def index
    @recipes = Recipe.all
  end
  
    def show
    @recipe = Recipe.find(params[:id])
  end
  
  
  def new
    @recipe = Recipe.new
  end 
  
  
  def edit
    @recipe = Recipe.find(params[:id])
  end 

  
  def create
    @recipe = Recipe.new(recipe_params)
    
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'recipe was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end 
  
  
  def update
        @recipe = Recipe.find(params[:id])
  
    if @recipe.update(recipe_params)
        redirect_to @recipe
    else
      render 'edit'
    end
  end
  
  
  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    
    redirect_to recipes_path
  end
  
  
    private
    def recipe_params
        params.require(:recipe).permit(:name, :avgSize, :calories, :toFat, :chol, :sod, :pot, :totalCarbs, :diFi, :sugs, :pro)
    end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_calc_helper.rb
module FoodCalcHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/food_calc/index.html.erb
<h1>Nutritional Calculator</h1>


<p>this web application will calculate the nutritional make up of any recipe you desire</p>
<%= link_to 'View the ingredients database', controller: 'ingredients' %>
<br/>
<br/>
<%= link_to 'View the recipes database', controller: 'recipes' %>

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>

<% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@ingredient.errors.count, "error") %> prohibited
        this ingredient from being saved:
      </h2>
      <ul>
        <% @ingredient.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :'average_serving_size_(g)' %><br>
    <%= f.number_field :avgSize, step: :any %>
  </p>

  <p>
    <%= f.label :calories %><br>
    <%= f.number_field :calories, step: :any %>
  </p>

  <p>
    <%= f.label :'total_fat_(g)' %><br>
    <%= f.number_field :toFat, step: :any %>
  </p>

  <p>
    <%= f.label :'cholesterol_(mg)' %><br>
    <%= f.number_field :chol, step: :any %>
  </p>

  <p>
    <%= f.label :'sodium_(mg)' %><br>
    <%= f.number_field :sod, step: :any %>
  </p>

  <p>
    <%= f.label :'potassium_(mg)' %><br>
    <%= f.number_field :pot, step: :any %>
  </p>

  <p>
    <%= f.label :'total_carbohydrates_(g)' %><br>
    <%= f.number_field :totalCarbs, step: :any %>
  </p>

  <div class="subValues">
  <p>
    &emsp;
    <%= f.label :'dietary_fiber_(g)' %><br>
    &emsp;
    <%= f.number_field :diFi, step: :any %>
  </p>

  <p>
    &emsp;
    <%= f.label :'sugars_(g)' %><br>
    &emsp;
    <%= f.number_field :sugs, step: :any %>
  </p>
  </div>

  <p>
    <%= f.label :'protein_(g)' %><br>
    <%= f.number_field :pro, step: :any %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/ingredients/edit.html.erb
<h1>Edit Ingredient</h1>

<%= link_to 'Back to database', ingredients_path %>

<br/>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<head>
<title>Ingredient Database</title>
</head>

<h1>Ingredient Database</h1>

<%= link_to 'Click here to add an ingredient to the database', new_ingredient_path %>
<br/>
<br/>
<%= link_to 'Back', controller: 'food_calc' %>
<br/>
<br/>
<table>
  <tr>
    <th>Name</th>
    <th>Average Serving Size (g)</th>
    <th>Calories</th>
    <th>Total fat (g)</th>
    <th>Cholesterol (mg)</th>
    <th>Sodium (mg)</th>
    <th>Potassium (mg)</th>
    <th>Total Carbohydrates (mg)</th>
    <th>Dietary Fibre (g)</th>
    <th>Sugars (g)</th>
    <th>Protein (g)</th>
    <th colspan="3"></th>
  </tr>
  
  <% @ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.name %></td>
        <td><%= ingredient.avgSize %></td>
        <td><%= ingredient.calories %></td>
        <td><%= ingredient.toFat %></td>
        <td><%= ingredient.chol %></td>
        <td><%= ingredient.sod %></td>
        <td><%= ingredient.pot %></td>
        <td><%= ingredient.totalCarbs %></td>
        <td><%= ingredient.diFi %></td>
        <td><%= ingredient.sugs %></td>
        <td><%= ingredient.pro %></td>
        <td><%= link_to 'Show', ingredient_path(ingredient) %></td>
        <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
        <td><%= link_to 'Delete', ingredient_path(ingredient), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/ingredients/new.html.erb
<h1>New Ingredient</h1>

<%= link_to 'Back', ingredients_path %>

<br/>

<%= render 'form' %>

app/views/ingredients/show.html.erb
<h1>New Ingredient Added</h1>

<table>
  <tr>
    <th>Name:</th>
    <th>Average Serving Size (g)</th>
    <th>Calories</th>
    <th>Total fat (g)</th>
    <th>Cholesterol (mg)</th>
    <th>Sodium (mg)</th>
    <th>Potassium (mg)</th>
    <th>Total carbohydrates (mg)</th>
    <th>Dietary fibre (g)</th>
    <th>Sugars (g)</th>
    <th>Protein (g)</th>
    <th></th>
  </tr>
  <tr>
    <td><%= @ingredient.name %></td>
    <td><%= @ingredient.avgSize %></td>
    <td><%= @ingredient.calories %></td>
    <td><%= @ingredient.toFat %></td>
    <td><%= @ingredient.chol %></td>
    <td><%= @ingredient.sod %></td>
    <td><%= @ingredient.pot %></td>
    <td><%= @ingredient.totalCarbs %></td>
    <td><%= @ingredient.diFi %></td>
    <td><%= @ingredient.sugs %></td>
    <td><%= @ingredient.pro %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(@ingredient) %></td>
  </tr>
</table>

<br/>
<%= link_to 'Add Another Ingredient', new_ingredient_path %>
<br/>
<br/>
<%= link_to 'View Ingredient Database', ingredients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodCalculator</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<head>
<title>Recipe Database</title>
</head>

<h1>Recipe Database</h1>

<%= link_to 'Click here to create a recipe', new_recipe_path %>
<br/>
<br/>
<%= link_to 'Back', controller: 'food_calc' %>
<br/>
<br/>
<table>
  <tr>
    <th>Name</th>
    <th>Servings</th>
    <th>Calories</th>
    <th>Total fat (g)</th>
    <th>Cholesterol (mg)</th>
    <th>Sodium (mg)</th>
    <th>Potassium (mg)</th>
    <th>Total Carbohydrates (mg)</th>
    <th>Dietary Fibre (g)</th>
    <th>Sugars (g)</th>
    <th>Protein (g)</th>
    <th colspan="4"></th>
  </tr>
  
  <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.servings %></td>
        <td><%= recipe.calories %></td>
        <td><%= recipe.toFat %></td>
        <td><%= recipe.chol %></td>
        <td><%= recipe.sod %></td>
        <td><%= recipe.pot %></td>
        <td><%= recipe.totalCarbs %></td>
        <td><%= recipe.diFi %></td>
        <td><%= recipe.sugs %></td>
        <td><%= recipe.pro %></td>
        <td><%= link_to 'Show', recipe_path(recipe) %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Delete', recipe_path(recipe), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
    </tr>
  <% end %>

app/views/recipes/new.html.erb
<%= form_for @recipe do |f| %>

<% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@recipe.errors.count, "error") %> prohibited
        this recipe from being saved:
      </h2>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <form method = "get"> 
    <p>
        <label for="ingredients">ingredients:</label>
        <select name="ingredients" id="ingredients">
          <% @ingredients.each do |ingredient| %>
          
          <option value="<%= ingredient.name %>"><%= ingredient.name %></option>
          
          <% end %>
          
                </select> <!--different breed options are made-->
    </p>
    <p>
        <label for:"name">Name:</label>
        <input type="text" name="name" id="name">
    </p>
     <p>
        <label for:"age">Age:</label>
        <input type="int" name="age" id="age">
    </p>
    <input type="submit" value="submit" onclick="addtoDB()"> <!--if the button is clicked then the addtoDB() function will be executed-->
</form>
  <p>
    <%= f.label :servings %><br>
    <%= f.number_field :servings %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>